version: 1
formatters:
  simple:
    format: "%(asctime)s %(name)-16s %(levelname)-8s %(message)s"
    datefmt: "[%Y/%m/%d-%H:%M:%S]"
  colored:
    class: colorlog.ColoredFormatter
    format: "%(blue)s%(asctime)s%(reset)s %(name)-16s %(log_color)s%(levelname)-8s%(reset)s %(message)s"
    datefmt: "[%Y/%m/%d-%H:%M:%S]"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  colored_tail:
    class: logging.FileHandler
    filename: ./logs/tail
    level: DEBUG
    formatter: colored
    encoding: utf-8
  file:
    class: logging.FileHandler
    filename: ./logs/latest.log
    level: DEBUG
    formatter: simple
    encoding: utf-8
loggers:
  Biggs:
    level: DEBUG
    handlers: [console, file, colored_tail]
    propagate: no
  discord:
    level: INFO
    handlers: [console, file, colored_tail]
