# Tokens:
#   You need to create a Discord Application, enable a bot for it, and get its token.
#   https://discord.com/developers/applications/
# IDs:
#   You can get guild, channel, and role IDs by right-clicking them with Developer Mode enabled.

smalls:
  token: FILL_THIS_IN
  command_prefix: "."

  lavalink_path: ./lavalink
  lavalink_args: -Xms1g -Xmx2g

biggs:
  token: FILL_THIS_IN
  command_prefix: ","

  # Server the bot operates in
  guild_id: REQUIRED
  # Channel the bot sends administrative notices to
  notice_channel_id: REQUIRED
  # Channels the bot does not monitor
  ignored_channels: []
    # - 000000000000000000

  # Roles considered "moderator" roles for restricting access to commands
  mod_roles:
    - REQUIRED

  # Emoji for command feedback.
  # Use the ID (number)
  reactions:
    header:   "\U0001F34A" # :tangerine:
    confirm:  "\U00002705" # :white_check_mark:
    deny:     "\U0000274c" # :x:
    confused: "\U00002754" # :grey_question:
